swagger: '2.0'
info:
  title: GonnaTrackYou
  description: Letting you know how cool you are!
  version: "0.1"
  contact:
    name: Dário T A for Cool Apps Ltd.
    email: tech@iDlySystems.com
host: "localhost:12345"
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /login:
    post:
      # this had a space in it, but it breaks html2 docs for some reason
      operationId: LoginUser
      summary: Login or create a user from a token
      description: |
        Takes a user's access token for Facebook, validates, and extends it through Graph API. It then creates a user locally if needed, or informs the client if they should prompt the user to accept some permission they denied.
      parameters:
        - name: accessToken
          in: query
          required: true
          type: string
          description: The user's short lived access token as returned by Facebook.
      responses:
        200:
          description: The token passed validation and the user already existed or one was created with all requisite permissions. The access information will be set in a session cookie, but is also returned in the body for devices where cookies aren't (easily) supported. The denied permissions list will be empty.
          schema:
            $ref: '#/definitions/CreateResponse'
          headers:
            Access-Control-Allow-Origin:
              type: string
        202:
          description: The token passed validation and a new user was created, but some permissions were denied. These will be listed in the body and the user should be given a description of why these permissions are needed and an option to log in again (hopefully accepting the permissions). The session cookie is created as in the 200 response.
          schema:
            $ref: '#/definitions/CreateResponse'
          headers:
            Access-Control-Allow-Origin:
              type: string
        401:
          description: The token failed validation.
          headers:
            Access-Control-Allow-Origin:
              type: string
        500:
          description: Unexpected error occurred. May ignore the Accept header, not include CORS headers, etc. As such, the client should not attempt to inspect the body.
definitions:
  CreateResponse:
    description: Describes the result of a user creation attempt.
    type: object
    properties:
      data:
        description: A (potentially empty) list of rejected permissions in generating the token.
        type: array
        items:
          $ref: '#/definitions/Permission'
      meta:
        type: object
        properties:
          accessInfo:
            type: object
            properties:
              userId:
                type: string
                description: The user ID of the authenticated user.
              token:
                type: string
                description: A login token for this device.
  Permission:
    type: object
    properties:
      id:
        type: string
        description: The name of the permission this object represents, as returned by Graph API.
      type:
        type: string
        description: Always "permission". Required for conformance to JSON API specification.
